bark-no-dog-spec/config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get "/log-in" => "sessions#new", as: :log_in
  post "/log-in" => "sessions#create"
  delete "/log-out" => "sessions#destroy", as: :log_out
  resources :dogs do
    resources :statuses
  end
  get "/profile" => "dogs#profile", as: :profile
end

bark-no-dog-spec/app/models/dog.rb
class Dog < ActiveRecord::Base

  has_secure_password
  
  validates_presence_of :name, :city, :state, :email

  validates_uniqueness_of :email

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  has_many :statuses

  scope :newsletter_subscribers, -> { where(newsletter: true)}

  def birthday?
    birthday.month == Time.now.month && birthday.day == Time.now.day
  end

  def age  # Test to make sure age is actually taking the current year minus the birth year
    Time.now.year - birthday.year
  end

  def location
    city + ", " + state
  end

  def puppy?
    age < 1
  end

  def age_in_dog_years
    age * 7
  end

  def subscribe_to_newsletter
    self.newsletter = true
    save
  end

  def unsubscribe_from_newsletter
    self.newsletter = false
    save
  end

end

bark-no-dog-spec/app/models/status.rb
class Status < ActiveRecord::Base
  belongs_to :dog

  validates_presence_of :dog_id, :body
end

bark-no-dog-spec/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_dog
    @current_dog ||= Dog.find(session[:dog_id]) if session[:dog_id]
  end

  helper_method :current_dog
end

bark-no-dog-spec/app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]

  def index
    @dogs = Dog.all
  end

  def show
    
  end

  def new
    @dog = Dog.new
  end

  def edit
  end

  def create
    @dog = Dog.new(dog_params)
    if @dog.save
      redirect_to @dog, notice: 'Dog was successfully created.'
    else
      render :new
    end
  end

  def update
    if @dog.update(dog_params)
      redirect_to @dog, notice: 'Dog was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @dog.destroy
    redirect_to dogs_url, notice: 'Dog was successfully destroyed.'
  end

  def profile
    @dog = current_dog
  end

  private
   
  def set_dog
    @dog = Dog.find(params[:id])
  end

  
  def dog_params
    params.require(:dog).permit(:name, :email, :password, :birthday, :city, :state, :newsletter, :avatar)
  end
end

bark-no-dog-spec/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

bark-no-dog-spec/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @dog = Dog.find_by_email(params[:email])
    if @dog && @dog.authenticate(params[:password])
      session[:dog_id] = @dog.id
      flash[:notice] = "Walked in the doggy door successfully."
    else
      flash[:alert] = "There was a problem, you're in the doghouse."
    end
    redirect_to root_path
  end

  def destroy
    session[:dog_id] = nil
    flash[:notice] = "You've been taken for a walk successfully and signed out."
    redirect_to root_path
  end

end

bark-no-dog-spec/app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  def index
    @dog = current_dog
    @statuses = Status.all
  end

  def show
  end

  def new
    @status = Status.new
    @status.dog_id = params[:dog_id]
  end

  def edit
  end

  def create
    @status = Status.new(status_params)
    @status.dog_id = params[:dog_id]
    if @status.save
      redirect_to @status.dog, notice: 'Status was successfully created.'
    else
      render :new
    end
  end

  def update
    if @status.update(status_params)
      redirect_to [@status.dog, @status], notice: 'Status was successfully updated.'
    else
      render :edit 
    end
  end

  def destroy
    @status.destroy
    redirect_to dog_statuses_url(@status.dog), notice: 'Status was successfully destroyed.'
  end

  private
  
  def set_status
    @status = Status.find(params[:id])
  end

  def status_params
    params.require(:status).permit(:body, :dog_id)
  end
end

bark-no-dog-spec/app/helpers/application_helper.rb
module ApplicationHelper
end

bark-no-dog-spec/app/helpers/dogs_helper.rb
module DogsHelper
end

bark-no-dog-spec/app/helpers/home_helper.rb
module HomeHelper
end

bark-no-dog-spec/app/helpers/statuses_helper.rb
module StatusesHelper
end

bark-no-dog-spec/app/views/dogs/_dog.html.erb
<div class="dog">
  <h3><%=link_to dog.name, dog_path(dog) %></h3>
  <%=image_tag dog.avatar, class: "dog-photo" %>
  <p>
    <%=dog.location %>
  </p>
  <% if dog.statuses.present? %>
    <h4>Recent Statuses</h4>
    <% dog.statuses.last(4).each do |status| %>
      <%=status.body %>
      <br>
      <%=status.created_at.strftime("%A, %d %b %Y %l:%M %p") %>
    <% end %>
  <% else %>
    No recent status updates.
  <% end %>
</div>
<br>

bark-no-dog-spec/app/views/dogs/_form.html.erb
<%= form_for @dog, :html => { :multipart => true }  do |f| %>
  <% if @dog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

      <ul>
      <% @dog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password  %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation  %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br>
    <%= f.date_select :birthday %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :newsletter %><br>
    <%= f.check_box :newsletter %>
  </div>
  <div class="field">
    <%= f.file_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

bark-no-dog-spec/app/views/dogs/edit.html.erb
<h1>Editing dog</h1>

<%= render 'form' %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', dogs_path %>

bark-no-dog-spec/app/views/dogs/index.html.erb
<h1>All Teh Dogs</h1>

<% @dogs.each do |dog| %>
  <%= render "dog", dog: dog %>
<% end %>

<br>

<%= link_to 'New Dog', new_dog_path %>

bark-no-dog-spec/app/views/dogs/new.html.erb
<h1>New dog</h1>

<%= render 'form' %>

<%= link_to 'Back', dogs_path %>

bark-no-dog-spec/app/views/dogs/profile.html.erb
<%=render "dog", dog: @dog %>

<%=link_to "Nuzzle keyboard new post", new_dog_status_path(@dog) %>

bark-no-dog-spec/app/views/dogs/show.html.erb
<%=render "dog", dog: @dog %>
<%= link_to 'Back', dogs_path %>

bark-no-dog-spec/app/views/home/index.html.erb
<% if current_dog %>
  <h1>Welcome to Bark, <%=current_dog.name %>!</h1>
<% else %>
  <h1>Welcome to Bark!</h1>
<% end %>
<h3>The only social network developed by dogs, for dogs</h3>

bark-no-dog-spec/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bark</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1 class="logo">
    <%=link_to "BARK", root_path %>
  </h1>
  <nav>
    <ul>
      <% if current_dog %>
        <li>
          <%=link_to "Log Out", log_out_path, method: :delete %>
        </li>
      <% else %>
        <li>
          <%=link_to "Log In", log_in_path %>
        </li>
        <li>
          <%=link_to "Sign Up", new_dog_path %>
        </li>
      <% end %>
      <li>
        <%=link_to "Dog News Feed", dogs_path %>
      </li>
      <li>
        <%=link_to "My Profile", profile_path %>
      </li>
    </ul>
  </nav>
  <div class="flash-wrapper">
    <% flash.each do |key, value| %>
      <div class="flash <%=key %>">
        <%=value %>
      </div>
    <% end %>
  </div>
  <%= yield %>

</body>
</html>

bark-no-dog-spec/app/views/statuses/_form.html.erb
<%= form_for [current_dog, @status] do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

bark-no-dog-spec/app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

bark-no-dog-spec/app/views/statuses/index.html.erb
<h1>Listing statuses</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Dog</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @statuses.each do |status| %>
      <tr>
        <td><%= status.body %></td>
        <td><%= status.dog_id %></td>
        <td><%= link_to 'Show', status %></td>
        <td><%= link_to 'Edit', edit_status_path(status) %></td>
        <td><%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Status', new_status_path %>

bark-no-dog-spec/app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

bark-no-dog-spec/app/views/statuses/show.html.erb
<p>
  <strong>Body:</strong>
  <%= @status.body %>
</p>

<p>
  <strong>Dog:</strong>
  <%= @status.dog_id %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>