old_assignment/config/routes.rb
Rails.application.routes.draw do

    root 'welcome#index'

  # get 'users/new'

  # get 'users/create'

  # get 'users/edit'

  # get 'users/udpate'

  # get 'users/index'

  # get 'users/show'

  # get 'users/destroy'

  # get 'sessions/new'

  get    'login'   => 'sessions#new'
  
  post   'login'   => 'sessions#create'

  get 'logout' => 'sessions#destroy'

  resources :users
  resources :cards
  resources :user_cards

  # You can have the root of your site routed with "root"



end

old_assignment/app/models/card.rb
class Card < ActiveRecord::Base

	has_many :user_cards
	has_many :users, through: :user_cards

	validates :expires_month, inclusion: {in: 1..12}
	validates :number, presence: true, uniqueness:true, length: {minimum: 4}

end

old_assignment/app/models/user.rb
class User < ActiveRecord::Base

	has_many :user_cards
	has_many :cards, through: :user_cards

	validates :password, confirmation: true, presence: true, :length => { :in => 6..100 }
	validates :fname, presence: true
	# validates :lname, presence: true
	# validates :email, presence: true, uniqueness: true
	# validates :balance, numericality: { greater_than_or_equal_to: 0}
	# has_secure_password
	# before_create  :fix_email
	# need to add phone validation before_update :fix_phone_format
	# after_update :fix_phone_format

	def to_s
		"#{self.fname} #{self.lname}"
	end

	attr_accessor :password_salt, :password_digest
	# def fix_phone_number
	# 	puts "TROY >>>>>>>>>>>>>>>>>>> User.before_save()"
	# 	updated = self.phone_number.gsub("\s", "")
	# 	self.phone_number = updated
	# end

	# :fix_phone_number,

	def fix_email
		updated = self.email.downcase
		self.email = updated
	end

	def fix_phone_format
		cleanup = self.phone.gsub("[ .,-]", "")
	end

end

old_assignment/app/models/user_card.rb
class UserCard < ActiveRecord::Base
  belongs_to :user
  belongs_to :card

  # def ownership
  # end
  	
end

old_assignment/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end
  
end

old_assignment/app/controllers/cards_controller.rb
class CardsController < ApplicationController

	def new
		@card = Card.new
		@user = User.all
	end

	def create
		@user = current_user
		card = Card.create(card_params)
		
		if card.persisted?
			flash[:notice]
			redirect_to cards_path(card)
		else
			flash[:notice] = "Sorry try again."
			redirect_to new_card_path
		end
	end

	def update

	end

	def show
		@card = Card.find(params[:id])
		@ownership = UserCard.find_by(user_id: 1, card_id: @card.id)
		# ToDo unhardcode user_id, change to session[:user_id]
		# find_by returns an item if there is an ownership
		# otherwise returns nil
	end

	def destroy
		Card.find(params[:id]).destroy
		redirect_to cards_path
	end

	def index
		@cards = Card.all
	end

	private

	def card_params
		params.require(:card).permit(:number, :cardtype, :expires_month, :expires_year, :code)
	end


end

old_assignment/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		result = User.all.where(
			email: params[:email], password: params[:password]).first
		if result
			flash[:notice] = "You have logged in!"
			redirect_to user_path result
		else
			flash[:notice] = "invalid login/password. Please try again."
			redirect_to "/login"
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:notice] = "You have logged out."
		redirect_to users_path
	end

end

old_assignment/app/controllers/user_cards_controller.rb
class UserCardsController < ApplicationController

	def create
		puts "UsersCardsController.create()"
		# user_id = params[:user_id]
		# card_id = params[:card_id]
		# result = UserCard.create(params.permit(:user_id).permit(:card_id))
		result = UserCard.create(
			user_id: params[:user_id],
			card_id: params[:card_id]
		)
		# user_id = session[:user_id]
		# card_id = params[:card][:id]
		flash[:notice] = "Card Added"
		redirect_to user_cards_path
	end

	def index
		@user_cards = UserCard.all
	end

	def destroy
		uc = UserCard.find(params[:id])
		card_id = uc.card.id
		uc.destroy

		redirect_to card_path(card_id)
	end

end

old_assignment/app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update, :destroy]


	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to users_path
			puts "User Created"
		else
			render :new

		# else 
		# 	flash[:notice] = "User not created."
		# redirect_to new_user_path
		end
	end

def show
		# puts "Calling users#show with #{params[:id]}"
		# @user = User.find(params[:id])
	end

	def edit
		puts "This is edit"
	end

	def destroy
		User.find(params[:id]).destroy
		redirect_to users_path
	end

	private

	def set_user
		@user = User.find(params[:id])
	end

	def user_params
		params.require(:user).permit(:fname, :lname, :email, :phone, :balance, :password, :password_confirmation)
	end

end

old_assignment/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

old_assignment/app/helpers/application_helper.rb
module ApplicationHelper
end

old_assignment/app/helpers/cards_helper.rb
module CardsHelper
end

old_assignment/app/helpers/sessions_helper.rb
module SessionsHelper
end

old_assignment/app/helpers/user_cards_helper.rb
module UserCardsHelper
end

old_assignment/app/helpers/users_helper.rb
module UsersHelper

	def display_in_list(users)

		# content_tag(:p, "Rails HTML content builder")

		content_tag(:ul) do
			users.each do |users|
				concat content_tag(:li, users)
			end
		end
	end

end

old_assignment/app/helpers/welcome_helper.rb
module WelcomeHelper
end

old_assignment/app/views/cards/index.html.erb
<% @cards.each do |c| %>
<p>

	<div class="cards_list">
		<p>Card Number: <%= c.number %></p>
		<p>Card Type: <%= c.cardtype %></p>
		<p>Expiration Month: <%= c.expires_month %></p>
		<p>Expiration Year: <%= c.expires_year %></p>
		<%= link_to "delete", card_path(c.id), method: :delete %>
		<%= link_to "add to wallet",user_cards_path(card_id: c.id, user_id: 2), method: :post %>
	</div>

</p>

<% end %> 


<!-- Need to unharddocde  user_id using session[:user_id] -->

<!-- user_id: session[:user_id] -->
<!-- ? possibly user_card_path -->

old_assignment/app/views/cards/new.html.erb
<h1>Add Card</h1>

<%= form_for @card do |c| %>
<%= c.label :number  %>
<%= c.text_field :number %>

<%= c.label :cardtype  %>
<%= c.text_field :cardtype %>

<%= c.label :expires_month %>
<%= c.text_field :expires_month %>

<%= c.label :expires_year %>
<%= c.text_field :expires_year %>

<%= c.label :code  %>
<%= c.text_field :code %>

<%= c.submit :create %>

<% end %>
<p> <%= @current_user %> </p>

old_assignment/app/views/cards/show.html.erb
<p> Card Number: <%= @card.number %></p>
<p> Card Type: <%= @card.cardtype %></p>
<p> Expired Month: <%= @card.expires_month %></p>
<p> Expired Year: <%= @card.expires_year %></p>
<p> Card CVV: <%= @card.code %></p>

<% if ! @ownership.nill? %>
	<%= link_to("add to my wallet", user_cards_path(card_id: @card.id, user_id: 1), method: :post) %>
<% else %>

<%= link_to("remove from my wallet", user_card_path(card_id: @card.id, user_id: 1), method: :delete) %>
<% end %>

old_assignment/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Wallet</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<div id="container">
		<p><%= Time.now %></p>
		<% if flash[:notice] %>
		<div class="notice"><%= flash[:notice] %></div>
		<% end %>

		<%= yield %>
		<div id="float_clear"></div>
		<div class = "navbar navbar-inverse navbar-fixed-top">
			<div class = "navbar-inner">
				<nav>
					<ul>
						<li>
							<%= link_to "Signup", new_user_path %>
						</li>
						<li>
							<%= link_to "Users", users_path %>
						</li>
						<li>
							<%= link_to "Log In", login_path %>
						</li>
						<li>
							<%= link_to "Log Out", logout_path %>
						</li>
						<li>
							<%= link_to "All Cards", cards_path %>
						</li>
					</ul>
				</nav>

			</div>
		</div>
</div>
</body>
</html>

old_assignment/app/views/user_cards/index.html.erb
index.html.erb

<% @user_cards.each do |uc| %>
<p><%= uc.user.fname %>></p>

<% end %>

old_assignment/app/views/users/edit.html.erb
<%= form_for(@user, method: :put) do |f| %>

<%= f.label :fname, "First Name" %>
<%= f.text_field :fname %>

<%= f.label :lname, "Last Name" %>
<%= f.text_field :lname %>

<%= f.label :email, "Email" %>
<%= f.text_field :email %>

<%= f.label :password, "Password" %>
<%= f.text_field :password %>

<%= f.label :phone, "Phone Number" %>
<%= f.text_field :phone %>



<%= f.submit %>

<% end %>

old_assignment/app/views/users/index.html.erb
<%= display_in_list(@users) %>

old_assignment/app/views/users/new.html.erb
<%= form_for @user do |f| %>

<%= f.label :fname, "First Name" %>
<%= f.text_field :fname %>
<br>
<%= f.label :lname, "Last Name" %>
<%= f.text_field :lname %>
<br>
<%= f.label :email, "Email" %>
<%= f.text_field :email %>
<br>
<%= f.label :password, "Password" %>
<%= f.password_field :password %>
<br>
<%= f.label :password_confirmation, "Verify Password" %>
<%= f.password_field :password_confirmation %>
<br>
<%= f.submit %>

<% end %>

<%= link_to 'Back', users_path %>

old_assignment/app/views/users/show.html.erb
<!-- <p>Did you know that <%=@user.fname %> <%= @user.lname %> is wanted in <%= rand(20) %> different states?</p>
<p> This account was created <%= distance_of_time_in_words(Time.now, @user.created_at) %> ago </p>

<%= link_to "Add Card", new_card_path(@user) %>

<%= link_to("delete", user_path(@user.id), method: :delete)%>
<%= link_to("edit", edit_user_path(@user.id))%> -->

old_assignment/app/views/welcome/index.html.erb
Welcome to this page.